### PR TITLE
Adding new AWS recovery to new Orchestrator repo

### PR DESCRIPTION
**Pull request by skitch210**
This is same script in Powershell repo. We want to start making Orchestrator specific scripts here. This script allows for individual VMs to recover to AWS EC2 from an orchestration plan

### CODE REVIEW

**Comment by carceneaux** [comment]
@skitch210 Once this script has been added to this repository, please remove it from the other VeeamHub repo. This will eliminate any confusion as well as guide folks to this new repository. If you require assistance, please let me know.

@tsmithco I'll let you review/approve this PR. Key thing to pay attention to will be naming schemes of scripts/folders as well as validating documentation provided is sufficient. I can assist here as well if you need it.

**Comment by tsmithco** [comment]
@skitch210 Can you add in Orchestrator version required into the readme as well? 
Also, let's rename the script by removing VRO- from the beginning as well as changing Readme.md to reflect.

**Comment by skitch210** [comment]
Is that better?

**Comment by fawazh224** [comment]
Looks good to me!

**Pull request merged**
